# Generated by Django 5.0.2 on 2024-02-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiKey', models.CharField(max_length=420)),
                ('projectid', models.CharField(max_length=420)),
                ('appid', models.CharField(max_length=420)),
                ('authDomain', models.CharField(max_length=420)),
                ('storageBucket', models.CharField(max_length=420)),
                ('messagingSenderId', models.CharField(max_length=420)),
                ('measurementId', models.CharField(max_length=420)),
            ],
        ),
        migrations.CreateModel(
            name='FirebaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.data')),
            ],
        ),
    ]
